default:
  spec_file: "your_experimental_specs.csv"
  bg_cutoff: 0.99
  controls_pattern: "Controls"
  beads_pattern: "Beads"
  controls_index: !expr c(1, 2, 3, 4, 5) # (Unstained, FL1, FL3, FL6, FL11)
  comp_pattern: "-A"
  manual_comp: FALSE
  density_th: 1e-3
